#+SETUPFILE: ._setup.org
#+INCLUDE: ._leviathan-avc.org
#+TITLE: The start of something new...

So this is the start of work to start a new blog.  The thought process
is something like this...

"Hey I should write an article on this!... but I don't have anywhere
to put it and really don't want to create it at the moment"

* It Begins...

So far this blog is generated by Org-Mode Publish, in a basic form,
and hosted on Github, served via Github pages.  Originally I was
looking into bootstrap, but found it was just to difficult to modify
the css into doing what I wanted instead of what it wanted.

That being said, I ended up on Skeleton for something nice and
lightweight, but still had issues with div classes etc. not lining up
with what was expected.  As a result a tiny bit of javascript was
added merely to encapsulate various elements.  Given that I had to do
this with skeleton, I now wonder if maybe I shouldn't have just done
this with bootstrap as well...

Oh well, live and learn.

* Still to come

Next up is to look into organization of content and start writing some
basic content.  Along with this I need to look into using org's new
RSS backend to possibly create an rss feed for the site, or at least
the blog sometime, but I am not hugely worried about that honestly.

