#+SETUPFILE: ../._setup.org
#+TITLE: The start of something new

#+BEGIN_HTML
---
layout: page
title: {{{title}}}
tagline: Something new this way comes
category: Website
tags: [website, emacs, org-mode, org-publish, bootstrap, skeleton]
---
#+END_HTML
So this is the start of work to start a new blog.  The thought process
is something like this...

"Hey I should write an article on this!... but I don't have anywhere
to put it and really don't want to create it at the moment"

* It begins...
** Org-Mode Publish

This journey began with exploring just Emacs' Org-Mode Publish
functionality, but it was determined that it just wasn't a simple
enough process to update a list of articles, vs posts, vs anything
else.

** Jekyll/Github-Pages

After this I decided to look into Jekyll itself, which does in fact
provide the needed functionality.  After a little digging, I decided
to start with Jekyll-Bootstrap, which provides a basic environment for
integrating bootstrap into Jekyll, which is what Github-Pages uses.
After more digging I found a fork of Jekyll-Bootstrap that uses
Bootstrap v3, which I have switched to.

* Frameworks

In terms of frameworks, I settled on bootstrap after going through a
couple options.  I actually started with bootstrap when using
Org-Publish, but decided the amount of work required to integrate the
required structure into the exported documents from org, was more than
would have been worth it, and required a lot of scripting, which I
would rather not depend on for this, as some people choose not to use
javascript and I wanted something that would fail smoothly in that
case.

I then looked at Skeleton, which required far less work, and was much
more basic, which isn't a bad thing. As I got farther and farther
into it, it was going to take more work than I personally wanted to
invest to get the functionality I wanted out of the site.  I ended up
going back to bootstrap in the end just due to the amount of work
already done in it.

** Issues with Frameworks

My main issue with bootstrap, and indeed most frameworks, has to do
with the purpose of CSS vs HTML styling.  CSS is intended to be able
to style any created HTML document smoothly, without having to change
the content, however frameworks often require the content to be
structured in a certain way, or a large amount of work done to the
framework.  As a result it almost seems counter to the purpose to use
a framework at times.  However I have decided that since i can export
only the body of a document, limiting the amount of customization
required, especially when paired with Jekyll, that it will serve my
needs for now at least, as I can always change the styling without
modifing the content of the document.

* Still to come

As of today, November 28 2013, the site is still under progress.  I am
however finding I am getting to a point to start really writing some
of the content, as the basic structure is in place, hopefully starting
with an entry page etc. but also adding articles, and other documents
as I go along.

