#+SETUPFILE: ../._setup.org
#+TITLE: The start of something new...

#+BEGIN_HTML
---
layout: page
title: {{{title}}}
tagline: Something new this way comes
---
#+END_HTML
So this is the start of work to start a new blog.  The thought process
is something like this...

"Hey I should write an article on this!... but I don't have anywhere
to put it and really don't want to create it at the moment"

* It Begins...

So far this blog is generated by Org-Mode Publish, in a basic form,
and hosted on Github, served via Github pages.  It has already gone
through a few different versions, finally ending up back on bootstrap
where I started.

The funny thing, and after some time I may make a post on this, is
bootstrap, and indeed many frameworks, seem somewhat backwards in a
way.  The goal of CSS would be that you can style the same content
many ways, but to match the framework you have to change your content
to match the styling really.

Oh well, live and learn.

* Still to come

Next up is to look into organization of content and start writing some
basic content.  Along with this I need to look into using org's new
RSS backend to possibly create an rss feed for the site, or at least
the blog sometime, but I am not hugely worried about that honestly.

